### ISSUE TITLE
pluton: etcd scale test is failing

### ISSUE THREAD

**Issue by pbx0** [coreos/mantle#567] opened 2017-04-19 20:44 UTC
This is a continuation of issue: https://github.com/coreos/etcd-operator/issues/934 opened in a different repo as requested with logs. Reproduction steps I will write in a second comment forthcoming.

cc @yifan-gu @hongchaodeng

I just reproduced this first try using bootkube master and pluton master. It failed while scaling up to 3 nodes. (kubernetes 1.6.1, etcd-operator v0.2.4) Logs:

```
$ ./kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY     STATUS                  RESTARTS   AGE
kube-system   etcd-operator-1869680742-lkzd9            1/1       Running                 1          17m
kube-system   kube-apiserver-482rh                      1/1       Running                 0          6m
kube-system   kube-apiserver-6rphn                      1/1       Running                 0          6m
kube-system   kube-apiserver-m8fwl                      1/1       Running                 4          17m
kube-system   kube-controller-manager-264856076-fhwdg   1/1       Running                 1          17m
kube-system   kube-controller-manager-264856076-g9bq3   1/1       Running                 0          17m
kube-system   kube-dns-2431531914-9thwh                 3/3       Running                 0          17m
kube-system   kube-etcd-0000                            1/1       Running                 0          16m
kube-system   kube-etcd-0001                            0/1       Init:CrashLoopBackOff   6          6m
kube-system   kube-etcd-network-checkpointer-9s1jc      1/1       Running                 0          17m
kube-system   kube-etcd-network-checkpointer-gg17v      1/1       Running                 0          6m
kube-system   kube-etcd-network-checkpointer-r1mf1      1/1       Running                 0          6m
kube-system   kube-flannel-3kj3n                        2/2       Running                 0          11m
kube-system   kube-flannel-d9s6q                        2/2       Running                 1          6m
kube-system   kube-flannel-pnnkw                        2/2       Running                 0          17m
kube-system   kube-flannel-qrsll                        2/2       Running                 1          6m
kube-system   kube-proxy-1zzs1                          1/1       Running                 0          17m
kube-system   kube-proxy-h5l8n                          1/1       Running                 0          11m
kube-system   kube-proxy-svgrg                          1/1       Running                 0          6m
kube-system   kube-proxy-x492p                          1/1       Running                 0          6m
kube-system   kube-scheduler-2491364400-37v9w           1/1       Running                 0          17m
kube-system   kube-scheduler-2491364400-c28xp           1/1       Running                 2          17m
kube-system   pod-checkpointer-4lprw                    1/1       Running                 0          6m
kube-system   pod-checkpointer-4lprw-10.240.0.30        1/1       Running                 0          6m
kube-system   pod-checkpointer-lt5h9                    1/1       Running                 0          17m
kube-system   pod-checkpointer-lt5h9-10.240.0.4         1/1       Running                 0          17m
kube-system   pod-checkpointer-t1d0v                    1/1       Running                 0          6m
kube-system   pod-checkpointer-t1d0v-10.240.0.31        1/1       Running                 0          6m
```
```
./kubectl logs kube-etcd-0001 --namespace=kube-system
Error from server (BadRequest): container "etcd" in pod "kube-etcd-0001" is waiting to start: PodInitializing 
```

docker logs for kube-etcd-0001:
```
docker logs e5a473ecad35
Error:  etcdserver: Peer URLs already exists 
```
operator logs:
```
 time="2017-04-19T20:11:45Z" level=info msg="etcd-operator Version: 0.2.4"
time="2017-04-19T20:11:45Z" level=info msg="Git SHA: 7be6965"
time="2017-04-19T20:11:45Z" level=info msg="Go Version: go1.7.5"
time="2017-04-19T20:11:45Z" level=info msg="Go OS/Arch: linux/amd64"
E0419 20:11:45.195803       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:11:50.057198       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:11:55.987240       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:11:59.759303       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:04.130559       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:08.286924       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:12.975902       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:16.995542       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:21.051282       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:26.496493       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:30.283837       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0419 20:12:34.039522       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: the server does not allow access to the requested resource (get endpoints etcd-operator)
time="2017-04-19T20:12:38Z" level=info msg="finding existing clusters..." pkg=controller
time="2017-04-19T20:12:38Z" level=info msg="start running..." cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:12:38Z" level=info msg="starts running from watch version: 765" pkg=controller
time="2017-04-19T20:12:38Z" level=info msg="start watching at 765" pkg=controller
time="2017-04-19T20:12:46Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:12:46Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:12:54Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:12:54Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:13:02Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:13:02Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
 <...snip...>
 time="2017-04-19T20:20:23Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:20:23Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:20:28Z" level=info msg="spec update: from: {1 3.1.0 false 0xc420122500 <nil> <nil> 0xc420215690 <nil>} to: {3 3.1.0 false 0xc4200a7080 <nil> <nil> 0xc42011e890 <nil>}" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:20:36Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:20:36Z" level=info msg="running members: kube-etcd-0000" cluster-name=kube-etcd pkg=cluster
time="2017-04-19T20:20:36Z" level=info msg="cluster membership: kube-etcd-0000" cluster-name=kube-etcd pkg=cluster
```

tpr:
```
{
  "apiVersion": "etcd.coreos.com/v1beta1",
  "kind": "Cluster",
  "metadata": {
    "name": "kube-etcd",
    "namespace": "kube-system",
    "selfLink": "/apis/etcd.coreos.com/v1beta1/namespaces/kube-system/clusters/kube-etcd",
    "uid": "2c9562fb-253c-11e7-8b9a-42010af00004",
    "resourceVersion": "1822",
    "creationTimestamp": "2017-04-19T20:10:03Z"
  },
  "spec": {
    "TLS": null,
    "pod": {
      "antiAffinity": false,
      "nodeSelector": {
        "node-role.kubernetes.io/master": ""
      },
      "resources": {}
    },
    "selfHosted": {
      "bootMemberClientEndpoint": "http://10.240.0.4:12379"
    },
    "size": 3,
    "version": "3.1.0"
  },
  "status": {
    "conditions": [       {
        "reason": "Current cluster size: 0, desired cluster size: 1",
        "transitionTime": "2017-04-19T20:10:03.450783088Z",
        "type": "ScalingUp"
      },
      {
        "reason": "",
        "transitionTime": "2017-04-19T20:11:10.552463919Z",
        "type": "Ready"
      }
    ],
    "controlPaused": false,
    "currentVersion": "3.1.0",
    "members": {
      "ready": [
        "kube-etcd-0000"
      ]
    },
    "phase": "Running",
    "reason": "",
    "size": 1,
    "targetVersion": ""
  }
}
```

**Comment by pbx0** [comment] 2017-04-19 20:50
Reproduction steps:

1. checkout bootkube from master and build bootkube

2. checkpoint github.com/coreos/mantle

3. add the line: `defer platform.Manhole(c.Masters[0])` to the beginning of the function `func etcdScale(c *pluton.Cluster)` in this [file](https://github.com/coreos/mantle/blob/master/pluton/tests/bootkube/scale.go#L26)

4. run go imports on that file and execute the `./build` script from the root of the mantle repo to build pluton

5. run pluton etcd scale test:
./bin/pluton run --basename=<YOURNAME> \
--bootkubeScriptDir=<absolute Path to hack/quickstart  in the repo you built bootkube from> \ 
--bootkubeBinary=<absolute path to linux bootkube binary> \
 experimental.selfetcd.scale

Upon exit to the test (failure or not) you will be dropped into a shell with access to the master node of that test.

**Comment by hongchaodeng** [comment] 2017-04-20 22:30
```
etcdserver: Peer URLs already exists 
```
It might mean two etcd pods get scheduled onto same nodes. This might be a potential regression on 1.6 .

**Comment by ajeddeloh** [comment] 2017-11-21 22:24
Closing this since pluton has been dropped (https://github.com/coreos/mantle/pull/683).

**Closed by ajeddeloh** 2017-11-21 22:24 UTC
