### ISSUE TITLE
ore: aws: unable to find just uploaded AMI

### ISSUE THREAD

**Issue by cgwalters** [coreos/mantle#1091] opened 2019-10-10 23:30 UTC
Have seen this a few times lately:

```
2019-10-10 22:23:07.243431 I | platform/api/aws: deleting s3://rhcos-ci/testing/amis/rhcos-43devel.80.20191010.0-aws.x86_64.vmdk
2019-10-10 22:23:07.382143 I | platform/api/aws: Deleted existing S3 object bucket:rhcos-ci path:testing/amis/rhcos-43devel.80.20191010.0-aws.x86_64.vmdk
2019-10-10 22:23:07.690519 I | platform/api/aws: Deregistered existing image ami-0819b0e074c686b9c
2019-10-10 22:23:07.872217 I | platform/api/aws: found existing snapshot snap-0b7ef6cd6c87799d1
2019-10-10 22:23:22.574657 I | platform/api/aws: Deleted existing snapshot snap-0b7ef6cd6c87799d1
2019-10-10 22:23:23.454214 I | platform/api/aws: uploading s3://rhcos-ci/testing/amis/rhcos-43devel.80.20191010.0-aws.x86_64.vmdk
2019-10-10 22:23:33.639338 I | platform/api/aws: created snapshot import task import-snap-0179e7926947afa70
2019-10-10 22:30:54.958885 I | platform/api/aws: deleting s3://rhcos-ci/testing/amis/rhcos-43devel.80.20191010.0-aws.x86_64.vmdk
unable to create HVM image: couldn't tag image name: error creating tags: InvalidAMIID.NotFound: The image id '[ami-0ed6aa075ca18d129]' does not exist
	status code: 400, request id: 1e45dd43-4d79-4208-8906-b4fec3563b44
```

Might be an eventual consistency issue with uploaded AMIs; probably need to retry for a bit?

**Comment by jlebon** [comment] 2019-10-11 17:05
Seems like a dupe of https://github.com/coreos/mantle/issues/1030.

**Closed** 2019-10-12 00:42 UTC
